apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: helm-aws-external-secrets
  annotations:
    meta.crossplane.io/maintainer: Patrick Lee Scott
    meta.crossplane.io/source: github.com/hops-ops/helm-aws-external-secrets
    meta.crossplane.io/description: Installs external-secrets with AWS Pod Identity for Secrets Manager and SSM Parameter Store access.
spec:
  dependsOn:
  - function: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: ">=v0.6.0"
  - configuration: ghcr.io/hops-ops/helm-external-secrets
    version: ">=v0.2.0"
  - configuration: ghcr.io/hops-ops/aws-pod-identity
    version: ">=v0.5.0"
